// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_common.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "game_common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protocols {
namespace common {

namespace {

const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* MessageType_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* MessageAction_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* ENUM_ATTR_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_game_5fcommon_2eproto() {
  protobuf_AddDesc_game_5fcommon_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "game_common.proto");
  GOOGLE_CHECK(file != NULL);
  ErrorCode_descriptor_ = file->enum_type(0);
  MessageType_descriptor_ = file->enum_type(1);
  MessageAction_descriptor_ = file->enum_type(2);
  ENUM_ATTR_descriptor_ = file->enum_type(3);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_game_5fcommon_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_game_5fcommon_2eproto() {
}

void protobuf_AddDesc_game_5fcommon_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021game_common.proto\022\020protocols.common*\224\001"
    "\n\tErrorCode\022\016\n\nEC_SUCCESS\020\000\022\026\n\022EC_INVALI"
    "D_REQUEST\020\001\022\027\n\023EC_INVALID_ARGUMENT\020\002\022\017\n\013"
    "EC_IO_ERROR\020\003\022\020\n\014EC_NET_ERROR\020\004\022\017\n\013EC_DB"
    "_ERROR\020\005\022\022\n\016EC_ACTION_DENY\020\006*O\n\013MessageT"
    "ype\022\024\n\020MSG_TYPE_REQUEST\020\000\022\025\n\021MSG_TYPE_RE"
    "SPONSE\020\001\022\023\n\017MSG_TYPE_NOTIFY\020\002*\264\002\n\rMessag"
    "eAction\022\030\n\024MSG_ACTION_ACC_LOGIN\020\001\022\033\n\027MSG"
    "_ACTION_PLAYER_LOGIN\020\002\022\036\n\032MSG_ACTION_INI"
    "T_CONNECTION\020\003\022\037\n\033MSG_ACTION_GET_ACCOUNT"
    "_LIST\020\004\022\031\n\025MSG_ACTION_MOVE_START\020\005\022\034\n\030MS"
    "G_ACTION_CREATE_PLAYER\020\007\022\032\n\026MSG_ACTION_P"
    "LAYER_INFO\020\010\022 \n\034MSG_ACTION_BUDDY_DETAIL_"
    "INFO\020\t\022\030\n\024MSG_ACTION_HEARTBEAT\020\n\022\032\n\026MSG_"
    "ACTION_KICK_PLAYER\020\013*\355\006\n\tENUM_ATTR\022\010\n\004NO"
    "NE\020\000\022\006\n\002HP\020\001\022\n\n\006MAX_HP\020\002\022\007\n\003STA\020\003\022\014\n\010STR"
    "ENGTH\020\004\022\r\n\tTECHNIQUE\020\005\022\020\n\014INTELLIGENCE\020\006"
    "\022\n\n\006SPIRIT\020\007\022\t\n\005AGILE\020\010\022\016\n\nPHY_ATTACK\020\t\022"
    "\017\n\013PHY_DEFENCE\020\n\022\016\n\nMAG_ATTACK\020\013\022\017\n\013MAG_"
    "DEFENCE\020\014\022\016\n\nPHY_AT_HIT\020\r\022\016\n\nMAG_AT_HIT\020"
    "\016\022\020\n\014PHY_CRITICAL\020\017\022\030\n\024PHY_CRITICAL_DEFE"
    "NCE\020\020\022\020\n\014MAG_CRITICAL\020\021\022\030\n\024MAG_CRITICAL_"
    "DEFENCE\020\022\022\020\n\014PHY_AT_DODGE\020\023\022\020\n\014MAG_AT_DO"
    "DGE\020\024\022\023\n\017PHY_AT_HIT_RATE\020\025\022\023\n\017MAG_AT_HIT"
    "_RATE\020\026\022\025\n\021PHY_CRITICAL_RATE\020\027\022\035\n\031PHY_CR"
    "ITICAL_DEFENCE_RATE\020\030\022\025\n\021MAG_CRITICAL_RA"
    "TE\020\031\022\035\n\031MAG_CRITICAL_DEFENCE_RATE\020\032\022\025\n\021P"
    "HY_AT_DODGE_RATE\020\033\022\025\n\021MAG_AT_DODGE_RATE\020"
    "\034\022\t\n\005SPEED\020\035\022\023\n\017FIRE_RESISTANCE\020\036\022\022\n\016ICE"
    "_RESISTANCE\020\037\022\024\n\020SHOCK_RESISTANCE\020 \022\030\n\024F"
    "IRE_DAMAGE_INCREASE\020!\022\027\n\023ICE_DAMAGE_INCR"
    "EASE\020\"\022\031\n\025SHOCK_DAMAGE_INCREASE\020#\022\035\n\031PHY"
    "_DAMAGE_REDUCTION_RATE\020$\022\026\n\022PHY_CRI_MULT"
    "I_RATE\020%\022\026\n\022MAG_CRI_MULTI_RATE\020&\022\022\n\016MAG_"
    "COMBO_RATE\020\'\022\027\n\023COUNTER_ATTACK_RATE\020(\022\027\n"
    "\023DAMAGE_REBOUND_RATE\020)\022\016\n\nBLOOD_SUCK\020*\022\024"
    "\n\020ENUM_ATTR_NUMBER\020@", 1460);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "game_common.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_game_5fcommon_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_game_5fcommon_2eproto {
  StaticDescriptorInitializer_game_5fcommon_2eproto() {
    protobuf_AddDesc_game_5fcommon_2eproto();
  }
} static_descriptor_initializer_game_5fcommon_2eproto_;
const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ErrorCode_descriptor_;
}
bool ErrorCode_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* MessageType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageType_descriptor_;
}
bool MessageType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* MessageAction_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageAction_descriptor_;
}
bool MessageAction_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ENUM_ATTR_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ENUM_ATTR_descriptor_;
}
bool ENUM_ATTR_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
    case 38:
    case 39:
    case 40:
    case 41:
    case 42:
    case 64:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace common
}  // namespace protocols

// @@protoc_insertion_point(global_scope)
